"""create_quests_and_quest_steps

Revision ID: 2f662f9a2bd4
Revises: 2d8f0c78137f
Create Date: 2026-10-10 16:47:40.844955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f662f9a2bd4'
down_revision: Union[str, None] = '2d8f0c78137f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('reward_xp', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('destination_name', sa.String(length=255), nullable=False),
    sa.Column('destination_latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('destination_longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('verification_prompt', sa.Text(), nullable=False),
    sa.Column('verification_answer', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("difficulty IN ('easy', 'medium', 'hard')", name='ck_quests_difficulty_valid'),
    sa.CheckConstraint("status IN ('draft', 'active', 'completed', 'abandoned')", name='ck_quests_status_valid'),
    sa.CheckConstraint('estimated_minutes > 0', name='ck_quests_estimated_minutes_positive'),
    sa.CheckConstraint('reward_xp >= 0', name='ck_quests_reward_xp_nonnegative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quests_status'), 'quests', ['status'], unique=False)
    op.create_index(op.f('ix_quests_user_id'), 'quests', ['user_id'], unique=False)
    op.create_table('quest_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quest_id', sa.UUID(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('clue', sa.Text(), nullable=False),
    sa.Column('is_unlocked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('step_order >= 1', name='ck_quest_steps_step_order_positive'),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quest_id', 'step_order', name='uq_quest_steps_quest_id_step_order')
    )
    op.create_index(op.f('ix_quest_steps_quest_id'), 'quest_steps', ['quest_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quest_steps_quest_id'), table_name='quest_steps')
    op.drop_table('quest_steps')
    op.drop_index(op.f('ix_quests_user_id'), table_name='quests')
    op.drop_index(op.f('ix_quests_status'), table_name='quests')
    op.drop_table('quests')
    # ### end Alembic commands ###
