"""create_parties_and_sessions

Revision ID: a8220599a32a
Revises: 2f662f9a2bd4
Create Date: 2026-10-11 02:21:22.918440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8220599a32a'
down_revision: Union[str, None] = '2f662f9a2bd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('host_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('invite_token_hash', sa.String(length=64), nullable=True),
    sa.Column('invite_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('open', 'active', 'completed', 'disbanded')", name='ck_parties_status_valid'),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parties_host_id'), 'parties', ['host_id'], unique=False)
    op.create_index(op.f('ix_parties_invite_token_hash'), 'parties', ['invite_token_hash'], unique=True)
    op.create_index(op.f('ix_parties_status'), 'parties', ['status'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_token_hash'), 'sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('party_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('party_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('slot_number', sa.Integer(), nullable=False, comment='Slot 1 or 2 in two-player party. Maps to clue split assignment.'),
    sa.Column('nickname', sa.String(length=50), nullable=False, comment='Explorer nickname displayed to partner by default.'),
    sa.Column('consent_reveal_identity', sa.Boolean(), nullable=False, comment='Explicit consent to reveal real explorer name to partner.'),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('host', 'member')", name='ck_party_memberships_role_valid'),
    sa.CheckConstraint("status IN ('active', 'left', 'removed')", name='ck_party_memberships_status_valid'),
    sa.CheckConstraint('slot_number IN (1, 2)', name='ck_party_memberships_slot_valid'),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('party_id', 'user_id', name='uq_party_memberships_party_user')
    )
    op.create_index(op.f('ix_party_memberships_party_id'), 'party_memberships', ['party_id'], unique=False)
    op.create_index(op.f('ix_party_memberships_status'), 'party_memberships', ['status'], unique=False)
    op.create_index(op.f('ix_party_memberships_user_id'), 'party_memberships', ['user_id'], unique=False)
    op.create_table('party_quests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('party_id', sa.UUID(), nullable=False),
    sa.Column('quest_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('active', 'completed', 'abandoned')", name='ck_party_quests_status_valid'),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('party_id', name='uq_party_quests_party_id'),
    sa.UniqueConstraint('quest_id', name='uq_party_quests_quest_id')
    )
    op.create_index(op.f('ix_party_quests_party_id'), 'party_quests', ['party_id'], unique=False)
    op.create_index(op.f('ix_party_quests_quest_id'), 'party_quests', ['quest_id'], unique=False)
    op.create_table('member_verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('party_quest_id', sa.UUID(), nullable=False),
    sa.Column('membership_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('distance_meters', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('observation_answer_submitted', sa.String(length=255), nullable=True),
    sa.Column('reward_xp_awarded', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], ['party_memberships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['party_quest_id'], ['party_quests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('party_quest_id', 'user_id', name='uq_member_verifications_quest_user')
    )
    op.create_index(op.f('ix_member_verifications_membership_id'), 'member_verifications', ['membership_id'], unique=False)
    op.create_index(op.f('ix_member_verifications_party_quest_id'), 'member_verifications', ['party_quest_id'], unique=False)
    op.create_index(op.f('ix_member_verifications_user_id'), 'member_verifications', ['user_id'], unique=False)
    op.create_table('split_clues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('party_quest_id', sa.UUID(), nullable=False),
    sa.Column('assigned_slot', sa.Integer(), nullable=False, comment='1 for explorer 1, 2 for explorer 2'),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('clue_title', sa.String(length=100), nullable=False),
    sa.Column('clue_text', sa.Text(), nullable=False),
    sa.Column('is_revealed', sa.Boolean(), nullable=False),
    sa.Column('revealed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('assigned_slot IN (1, 2)', name='ck_split_clues_assigned_slot_valid'),
    sa.CheckConstraint('step_order >= 1', name='ck_split_clues_step_order_positive'),
    sa.ForeignKeyConstraint(['party_quest_id'], ['party_quests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('party_quest_id', 'assigned_slot', 'step_order', name='uq_split_clues_slot_order')
    )
    op.create_index(op.f('ix_split_clues_party_quest_id'), 'split_clues', ['party_quest_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_split_clues_party_quest_id'), table_name='split_clues')
    op.drop_table('split_clues')
    op.drop_index(op.f('ix_member_verifications_user_id'), table_name='member_verifications')
    op.drop_index(op.f('ix_member_verifications_party_quest_id'), table_name='member_verifications')
    op.drop_index(op.f('ix_member_verifications_membership_id'), table_name='member_verifications')
    op.drop_table('member_verifications')
    op.drop_index(op.f('ix_party_quests_quest_id'), table_name='party_quests')
    op.drop_index(op.f('ix_party_quests_party_id'), table_name='party_quests')
    op.drop_table('party_quests')
    op.drop_index(op.f('ix_party_memberships_user_id'), table_name='party_memberships')
    op.drop_index(op.f('ix_party_memberships_status'), table_name='party_memberships')
    op.drop_index(op.f('ix_party_memberships_party_id'), table_name='party_memberships')
    op.drop_table('party_memberships')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_token_hash'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_parties_status'), table_name='parties')
    op.drop_index(op.f('ix_parties_invite_token_hash'), table_name='parties')
    op.drop_index(op.f('ix_parties_host_id'), table_name='parties')
    op.drop_table('parties')
    # ### end Alembic commands ###
