"""create auth_rate_limit_entries table

Revision ID: f8466515b7e0
Revises: 604c5bfb88ca
Create Date: 2026-10-11 03:07:33.249164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8466515b7e0'
down_revision: Union[str, None] = '604c5bfb88ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_rate_limit_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_rate_limit_entries_key'), 'auth_rate_limit_entries', ['key'], unique=False)
    op.create_index(op.f('ix_auth_rate_limit_entries_timestamp'), 'auth_rate_limit_entries', ['timestamp'], unique=False)
    op.create_index('ix_rate_limit_key_timestamp', 'auth_rate_limit_entries', ['key', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rate_limit_key_timestamp', table_name='auth_rate_limit_entries')
    op.drop_index(op.f('ix_auth_rate_limit_entries_timestamp'), table_name='auth_rate_limit_entries')
    op.drop_index(op.f('ix_auth_rate_limit_entries_key'), table_name='auth_rate_limit_entries')
    op.drop_table('auth_rate_limit_entries')
    # ### end Alembic commands ###
